#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MDispatch.Droid.Resource", IsApplication=true)]

namespace MDispatch.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int color_coloredbackground = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int launcher_background = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int AddDamege = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Aktiv = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Archive = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int BackIconpage = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int BoxTruckSingleWheel1 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int BoxTruckSingleWheel10 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int BoxTruckSingleWheel11 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int BoxTruckSingleWheel12 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int BoxTruckSingleWheel13 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int BoxTruckSingleWheel14 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int BoxTruckSingleWheel15 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int BoxTruckSingleWheel16 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int BoxTruckSingleWheel17 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int BoxTruckSingleWheel18 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int BoxTruckSingleWheel19 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int BoxTruckSingleWheel2 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int BoxTruckSingleWheel20 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int BoxTruckSingleWheel3 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int BoxTruckSingleWheel4 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int BoxTruckSingleWheel5 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int BoxTruckSingleWheel6 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int BoxTruckSingleWheel7 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int BoxTruckSingleWheel8 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int BoxTruckSingleWheel9 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int BoxTruckWheelDually1 = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int BoxTruckWheelDually10 = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int BoxTruckWheelDually11 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int BoxTruckWheelDually12 = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int BoxTruckWheelDually13 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int BoxTruckWheelDually14 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int BoxTruckWheelDually15 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int BoxTruckWheelDually16 = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int BoxTruckWheelDually17 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int BoxTruckWheelDually18 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int BoxTruckWheelDually19 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int BoxTruckWheelDually2 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int BoxTruckWheelDually20 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int BoxTruckWheelDually3 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int BoxTruckWheelDually4 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int BoxTruckWheelDually5 = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int BoxTruckWheelDually6 = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int BoxTruckWheelDually7 = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int BoxTruckWheelDually8 = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int BoxTruckWheelDually9 = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int CargiVanChasissDuallyOrSingleWheel1 = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int CargiVanChasissDuallyOrSingleWheel10 = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int CargiVanChasissDuallyOrSingleWheel11 = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int CargiVanChasissDuallyOrSingleWheel12 = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int CargiVanChasissDuallyOrSingleWheel13 = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int CargiVanChasissDuallyOrSingleWheel14 = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int CargiVanChasissDuallyOrSingleWheel15 = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int CargiVanChasissDuallyOrSingleWheel16 = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int CargiVanChasissDuallyOrSingleWheel17 = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int CargiVanChasissDuallyOrSingleWheel2 = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int CargiVanChasissDuallyOrSingleWheel3 = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int CargiVanChasissDuallyOrSingleWheel4 = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int CargiVanChasissDuallyOrSingleWheel5 = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int CargiVanChasissDuallyOrSingleWheel6 = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int CargiVanChasissDuallyOrSingleWheel7 = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int CargiVanChasissDuallyOrSingleWheel8 = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int CargiVanChasissDuallyOrSingleWheel9 = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int CargoVanMustHaveWithDually1 = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int CargoVanMustHaveWithDually10 = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int CargoVanMustHaveWithDually11 = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int CargoVanMustHaveWithDually12 = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int CargoVanMustHaveWithDually13 = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int CargoVanMustHaveWithDually14 = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int CargoVanMustHaveWithDually15 = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int CargoVanMustHaveWithDually16 = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int CargoVanMustHaveWithDually17 = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int CargoVanMustHaveWithDually18 = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int CargoVanMustHaveWithDually19 = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int CargoVanMustHaveWithDually2 = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int CargoVanMustHaveWithDually20 = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int CargoVanMustHaveWithDually21 = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int CargoVanMustHaveWithDually22 = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int CargoVanMustHaveWithDually23 = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int CargoVanMustHaveWithDually3 = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int CargoVanMustHaveWithDually4 = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int CargoVanMustHaveWithDually5 = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int CargoVanMustHaveWithDually6 = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int CargoVanMustHaveWithDually7 = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int CargoVanMustHaveWithDually8 = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int CargoVanMustHaveWithDually9 = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int CheckPaymment = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int Close = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int Coupe1 = 2130837590;
			
			// aapt resource value: 0x7F020057
			public const int Coupe10 = 2130837591;
			
			// aapt resource value: 0x7F020058
			public const int Coupe11 = 2130837592;
			
			// aapt resource value: 0x7F020059
			public const int Coupe12 = 2130837593;
			
			// aapt resource value: 0x7F02005A
			public const int Coupe13 = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public const int Coupe14 = 2130837595;
			
			// aapt resource value: 0x7F02005C
			public const int Coupe15 = 2130837596;
			
			// aapt resource value: 0x7F02005D
			public const int Coupe16 = 2130837597;
			
			// aapt resource value: 0x7F02005E
			public const int Coupe17 = 2130837598;
			
			// aapt resource value: 0x7F02005F
			public const int Coupe18 = 2130837599;
			
			// aapt resource value: 0x7F020060
			public const int Coupe19 = 2130837600;
			
			// aapt resource value: 0x7F020061
			public const int Coupe2 = 2130837601;
			
			// aapt resource value: 0x7F020062
			public const int Coupe20 = 2130837602;
			
			// aapt resource value: 0x7F020063
			public const int Coupe21 = 2130837603;
			
			// aapt resource value: 0x7F020064
			public const int Coupe22 = 2130837604;
			
			// aapt resource value: 0x7F020065
			public const int Coupe23 = 2130837605;
			
			// aapt resource value: 0x7F020066
			public const int Coupe24 = 2130837606;
			
			// aapt resource value: 0x7F020067
			public const int Coupe25 = 2130837607;
			
			// aapt resource value: 0x7F020068
			public const int Coupe26 = 2130837608;
			
			// aapt resource value: 0x7F020069
			public const int Coupe27 = 2130837609;
			
			// aapt resource value: 0x7F02006A
			public const int Coupe28 = 2130837610;
			
			// aapt resource value: 0x7F02006B
			public const int Coupe29 = 2130837611;
			
			// aapt resource value: 0x7F02006C
			public const int Coupe3 = 2130837612;
			
			// aapt resource value: 0x7F02006D
			public const int Coupe30 = 2130837613;
			
			// aapt resource value: 0x7F02006E
			public const int Coupe31 = 2130837614;
			
			// aapt resource value: 0x7F02006F
			public const int Coupe32 = 2130837615;
			
			// aapt resource value: 0x7F020070
			public const int Coupe33 = 2130837616;
			
			// aapt resource value: 0x7F020071
			public const int Coupe34 = 2130837617;
			
			// aapt resource value: 0x7F020072
			public const int Coupe35 = 2130837618;
			
			// aapt resource value: 0x7F020073
			public const int Coupe36 = 2130837619;
			
			// aapt resource value: 0x7F020074
			public const int Coupe37 = 2130837620;
			
			// aapt resource value: 0x7F020075
			public const int Coupe38 = 2130837621;
			
			// aapt resource value: 0x7F020076
			public const int Coupe39 = 2130837622;
			
			// aapt resource value: 0x7F020077
			public const int Coupe4 = 2130837623;
			
			// aapt resource value: 0x7F020078
			public const int Coupe40 = 2130837624;
			
			// aapt resource value: 0x7F020079
			public const int Coupe41 = 2130837625;
			
			// aapt resource value: 0x7F02007A
			public const int Coupe42 = 2130837626;
			
			// aapt resource value: 0x7F02007B
			public const int Coupe43 = 2130837627;
			
			// aapt resource value: 0x7F02007C
			public const int Coupe5 = 2130837628;
			
			// aapt resource value: 0x7F02007D
			public const int Coupe6 = 2130837629;
			
			// aapt resource value: 0x7F02007E
			public const int Coupe7 = 2130837630;
			
			// aapt resource value: 0x7F02007F
			public const int Coupe8 = 2130837631;
			
			// aapt resource value: 0x7F020080
			public const int Coupe9 = 2130837632;
			
			// aapt resource value: 0x7F020081
			public const int Cruisemotorcycle1 = 2130837633;
			
			// aapt resource value: 0x7F020082
			public const int Cruisemotorcycle10 = 2130837634;
			
			// aapt resource value: 0x7F020083
			public const int Cruisemotorcycle11 = 2130837635;
			
			// aapt resource value: 0x7F020084
			public const int Cruisemotorcycle2 = 2130837636;
			
			// aapt resource value: 0x7F020085
			public const int Cruisemotorcycle3 = 2130837637;
			
			// aapt resource value: 0x7F020086
			public const int Cruisemotorcycle4 = 2130837638;
			
			// aapt resource value: 0x7F020087
			public const int Cruisemotorcycle5 = 2130837639;
			
			// aapt resource value: 0x7F020088
			public const int Cruisemotorcycle6 = 2130837640;
			
			// aapt resource value: 0x7F020089
			public const int Cruisemotorcycle7 = 2130837641;
			
			// aapt resource value: 0x7F02008A
			public const int Cruisemotorcycle8 = 2130837642;
			
			// aapt resource value: 0x7F02008B
			public const int Cruisemotorcycle9 = 2130837643;
			
			// aapt resource value: 0x7F0201A9
			public const int custom_progressbar_style = 2130837929;
			
			// aapt resource value: 0x7F02008C
			public const int DamageD0 = 2130837644;
			
			// aapt resource value: 0x7F02008D
			public const int DamageD1 = 2130837645;
			
			// aapt resource value: 0x7F02008E
			public const int DamageD10 = 2130837646;
			
			// aapt resource value: 0x7F02008F
			public const int DamageD11 = 2130837647;
			
			// aapt resource value: 0x7F020090
			public const int DamageD12 = 2130837648;
			
			// aapt resource value: 0x7F020091
			public const int DamageD13 = 2130837649;
			
			// aapt resource value: 0x7F020092
			public const int DamageD14 = 2130837650;
			
			// aapt resource value: 0x7F020093
			public const int DamageD15 = 2130837651;
			
			// aapt resource value: 0x7F020094
			public const int DamageD16 = 2130837652;
			
			// aapt resource value: 0x7F020095
			public const int DamageD17 = 2130837653;
			
			// aapt resource value: 0x7F020096
			public const int DamageD18 = 2130837654;
			
			// aapt resource value: 0x7F020097
			public const int DamageD19 = 2130837655;
			
			// aapt resource value: 0x7F020098
			public const int DamageD2 = 2130837656;
			
			// aapt resource value: 0x7F020099
			public const int DamageD21 = 2130837657;
			
			// aapt resource value: 0x7F02009A
			public const int DamageD23 = 2130837658;
			
			// aapt resource value: 0x7F02009B
			public const int DamageD3 = 2130837659;
			
			// aapt resource value: 0x7F02009C
			public const int DamageD4 = 2130837660;
			
			// aapt resource value: 0x7F02009D
			public const int DamageD5 = 2130837661;
			
			// aapt resource value: 0x7F02009E
			public const int DamageD6 = 2130837662;
			
			// aapt resource value: 0x7F02009F
			public const int DamageD7 = 2130837663;
			
			// aapt resource value: 0x7F0200A0
			public const int DamageD8 = 2130837664;
			
			// aapt resource value: 0x7F0200A1
			public const int DamageD9 = 2130837665;
			
			// aapt resource value: 0x7F0200A2
			public const int DamageP0 = 2130837666;
			
			// aapt resource value: 0x7F0200A3
			public const int DamageP1 = 2130837667;
			
			// aapt resource value: 0x7F0200A4
			public const int DamageP10 = 2130837668;
			
			// aapt resource value: 0x7F0200A5
			public const int DamageP11 = 2130837669;
			
			// aapt resource value: 0x7F0200A6
			public const int DamageP12 = 2130837670;
			
			// aapt resource value: 0x7F0200A7
			public const int DamageP13 = 2130837671;
			
			// aapt resource value: 0x7F0200A8
			public const int DamageP14 = 2130837672;
			
			// aapt resource value: 0x7F0200A9
			public const int DamageP15 = 2130837673;
			
			// aapt resource value: 0x7F0200AA
			public const int DamageP16 = 2130837674;
			
			// aapt resource value: 0x7F0200AB
			public const int DamageP2 = 2130837675;
			
			// aapt resource value: 0x7F0200AC
			public const int DamageP23 = 2130837676;
			
			// aapt resource value: 0x7F0200AD
			public const int DamageP3 = 2130837677;
			
			// aapt resource value: 0x7F0200AE
			public const int DamageP4 = 2130837678;
			
			// aapt resource value: 0x7F0200AF
			public const int DamageP5 = 2130837679;
			
			// aapt resource value: 0x7F0200B0
			public const int DamageP6 = 2130837680;
			
			// aapt resource value: 0x7F0200B1
			public const int DamageP7 = 2130837681;
			
			// aapt resource value: 0x7F0200B2
			public const int DamageP8 = 2130837682;
			
			// aapt resource value: 0x7F0200B3
			public const int DamageP9 = 2130837683;
			
			// aapt resource value: 0x7F0201AA
			public const int deliveredViewOrder = 2130837930;
			
			// aapt resource value: 0x7F0200B4
			public const int Delivery = 2130837684;
			
			// aapt resource value: 0x7F0200B5
			public const int EnclosedTrailerTwoVehicles1 = 2130837685;
			
			// aapt resource value: 0x7F0200B6
			public const int EnclosedTrailerTwoVehicles10 = 2130837686;
			
			// aapt resource value: 0x7F0200B7
			public const int EnclosedTrailerTwoVehicles11 = 2130837687;
			
			// aapt resource value: 0x7F0200B8
			public const int EnclosedTrailerTwoVehicles12 = 2130837688;
			
			// aapt resource value: 0x7F0200B9
			public const int EnclosedTrailerTwoVehicles13 = 2130837689;
			
			// aapt resource value: 0x7F0200BA
			public const int EnclosedTrailerTwoVehicles2 = 2130837690;
			
			// aapt resource value: 0x7F0200BB
			public const int EnclosedTrailerTwoVehicles3 = 2130837691;
			
			// aapt resource value: 0x7F0200BC
			public const int EnclosedTrailerTwoVehicles4 = 2130837692;
			
			// aapt resource value: 0x7F0200BD
			public const int EnclosedTrailerTwoVehicles5 = 2130837693;
			
			// aapt resource value: 0x7F0200BE
			public const int EnclosedTrailerTwoVehicles6 = 2130837694;
			
			// aapt resource value: 0x7F0200BF
			public const int EnclosedTrailerTwoVehicles7 = 2130837695;
			
			// aapt resource value: 0x7F0200C0
			public const int EnclosedTrailerTwoVehicles8 = 2130837696;
			
			// aapt resource value: 0x7F0200C1
			public const int EnclosedTrailerTwoVehicles9 = 2130837697;
			
			// aapt resource value: 0x7F0200C2
			public const int FourDoorTruckChassisOpenFrame1 = 2130837698;
			
			// aapt resource value: 0x7F0200C3
			public const int FourDoorTruckChassisOpenFrame10 = 2130837699;
			
			// aapt resource value: 0x7F0200C4
			public const int FourDoorTruckChassisOpenFrame11 = 2130837700;
			
			// aapt resource value: 0x7F0200C5
			public const int FourDoorTruckChassisOpenFrame12 = 2130837701;
			
			// aapt resource value: 0x7F0200C6
			public const int FourDoorTruckChassisOpenFrame13 = 2130837702;
			
			// aapt resource value: 0x7F0200C7
			public const int FourDoorTruckChassisOpenFrame14 = 2130837703;
			
			// aapt resource value: 0x7F0200C8
			public const int FourDoorTruckChassisOpenFrame15 = 2130837704;
			
			// aapt resource value: 0x7F0200C9
			public const int FourDoorTruckChassisOpenFrame16 = 2130837705;
			
			// aapt resource value: 0x7F0200CA
			public const int FourDoorTruckChassisOpenFrame17 = 2130837706;
			
			// aapt resource value: 0x7F0200CB
			public const int FourDoorTruckChassisOpenFrame18 = 2130837707;
			
			// aapt resource value: 0x7F0200CC
			public const int FourDoorTruckChassisOpenFrame19 = 2130837708;
			
			// aapt resource value: 0x7F0200CD
			public const int FourDoorTruckChassisOpenFrame2 = 2130837709;
			
			// aapt resource value: 0x7F0200CE
			public const int FourDoorTruckChassisOpenFrame3 = 2130837710;
			
			// aapt resource value: 0x7F0200CF
			public const int FourDoorTruckChassisOpenFrame4 = 2130837711;
			
			// aapt resource value: 0x7F0200D0
			public const int FourDoorTruckChassisOpenFrame5 = 2130837712;
			
			// aapt resource value: 0x7F0200D1
			public const int FourDoorTruckChassisOpenFrame6 = 2130837713;
			
			// aapt resource value: 0x7F0200D2
			public const int FourDoorTruckChassisOpenFrame7 = 2130837714;
			
			// aapt resource value: 0x7F0200D3
			public const int FourDoorTruckChassisOpenFrame8 = 2130837715;
			
			// aapt resource value: 0x7F0200D4
			public const int FourDoorTruckChassisOpenFrame9 = 2130837716;
			
			// aapt resource value: 0x7F0200D5
			public const int GooseneckTrailerTwoVehicles1 = 2130837717;
			
			// aapt resource value: 0x7F0200D6
			public const int GooseneckTrailerTwoVehicles2 = 2130837718;
			
			// aapt resource value: 0x7F0200D7
			public const int GooseneckTrailerTwoVehicles3 = 2130837719;
			
			// aapt resource value: 0x7F0200D8
			public const int GooseneckTrailerTwoVehicles4 = 2130837720;
			
			// aapt resource value: 0x7F0200D9
			public const int GooseneckTrailerTwoVehicles5 = 2130837721;
			
			// aapt resource value: 0x7F0200DA
			public const int GooseneckTrailerTwoVehicles6 = 2130837722;
			
			// aapt resource value: 0x7F0200DB
			public const int GooseneckTrailerTwoVehicles7 = 2130837723;
			
			// aapt resource value: 0x7F0200DC
			public const int GooseneckTrailerTwoVehicles8 = 2130837724;
			
			// aapt resource value: 0x7F0200DD
			public const int GooseneckTrailerTwoVehicles9 = 2130837725;
			
			// aapt resource value: 0x7F0201AB
			public const int inScan = 2130837931;
			
			// aapt resource value: 0x7F0201AC
			public const int newOrder = 2130837932;
			
			// aapt resource value: 0x7F0201AD
			public const int newViewOrder = 2130837933;
			
			// aapt resource value: 0x7F0200DE
			public const int NotDamage = 2130837726;
			
			// aapt resource value: 0x7F0201AE
			public const int pickedUpOrder1 = 2130837934;
			
			// aapt resource value: 0x7F0201AF
			public const int pickedUpViewOrder = 2130837935;
			
			// aapt resource value: 0x7F0200DF
			public const int PickUp1 = 2130837727;
			
			// aapt resource value: 0x7F0200E0
			public const int PickUp10 = 2130837728;
			
			// aapt resource value: 0x7F0200E1
			public const int PickUp11 = 2130837729;
			
			// aapt resource value: 0x7F0200E2
			public const int PickUp12 = 2130837730;
			
			// aapt resource value: 0x7F0200E3
			public const int PickUp13 = 2130837731;
			
			// aapt resource value: 0x7F0200E4
			public const int PickUp14 = 2130837732;
			
			// aapt resource value: 0x7F0200E5
			public const int PickUp15 = 2130837733;
			
			// aapt resource value: 0x7F0200E6
			public const int PickUp16 = 2130837734;
			
			// aapt resource value: 0x7F0200E7
			public const int PickUp17 = 2130837735;
			
			// aapt resource value: 0x7F0200E8
			public const int PickUp18 = 2130837736;
			
			// aapt resource value: 0x7F0200E9
			public const int PickUp19 = 2130837737;
			
			// aapt resource value: 0x7F0200EA
			public const int PickUp2 = 2130837738;
			
			// aapt resource value: 0x7F0200EB
			public const int PickUp20 = 2130837739;
			
			// aapt resource value: 0x7F0200EC
			public const int PickUp21 = 2130837740;
			
			// aapt resource value: 0x7F0200ED
			public const int PickUp22 = 2130837741;
			
			// aapt resource value: 0x7F0200EE
			public const int PickUp23 = 2130837742;
			
			// aapt resource value: 0x7F0200EF
			public const int PickUp24 = 2130837743;
			
			// aapt resource value: 0x7F0200F0
			public const int PickUp25 = 2130837744;
			
			// aapt resource value: 0x7F0200F1
			public const int PickUp26 = 2130837745;
			
			// aapt resource value: 0x7F0200F2
			public const int PickUp27 = 2130837746;
			
			// aapt resource value: 0x7F0200F3
			public const int PickUp28 = 2130837747;
			
			// aapt resource value: 0x7F0200F4
			public const int PickUp29 = 2130837748;
			
			// aapt resource value: 0x7F0200F5
			public const int PickUp3 = 2130837749;
			
			// aapt resource value: 0x7F0200F6
			public const int PickUp30 = 2130837750;
			
			// aapt resource value: 0x7F0200F7
			public const int PickUp31 = 2130837751;
			
			// aapt resource value: 0x7F0200F8
			public const int PickUp32 = 2130837752;
			
			// aapt resource value: 0x7F0200F9
			public const int PickUp33 = 2130837753;
			
			// aapt resource value: 0x7F0200FA
			public const int PickUp34 = 2130837754;
			
			// aapt resource value: 0x7F0200FB
			public const int PickUp35 = 2130837755;
			
			// aapt resource value: 0x7F0200FC
			public const int PickUp4 = 2130837756;
			
			// aapt resource value: 0x7F0200FD
			public const int PickUp5 = 2130837757;
			
			// aapt resource value: 0x7F0200FE
			public const int PickUp6 = 2130837758;
			
			// aapt resource value: 0x7F0200FF
			public const int PickUp7 = 2130837759;
			
			// aapt resource value: 0x7F020100
			public const int PickUp8 = 2130837760;
			
			// aapt resource value: 0x7F020101
			public const int PickUp9 = 2130837761;
			
			// aapt resource value: 0x7F020102
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave21 = 2130837762;
			
			// aapt resource value: 0x7F020103
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave210 = 2130837763;
			
			// aapt resource value: 0x7F020104
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave211 = 2130837764;
			
			// aapt resource value: 0x7F020105
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave212 = 2130837765;
			
			// aapt resource value: 0x7F020106
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave213 = 2130837766;
			
			// aapt resource value: 0x7F020107
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave214 = 2130837767;
			
			// aapt resource value: 0x7F020108
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave215 = 2130837768;
			
			// aapt resource value: 0x7F020109
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave216 = 2130837769;
			
			// aapt resource value: 0x7F02010A
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave217 = 2130837770;
			
			// aapt resource value: 0x7F02010B
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave218 = 2130837771;
			
			// aapt resource value: 0x7F02010C
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave219 = 2130837772;
			
			// aapt resource value: 0x7F02010D
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave22 = 2130837773;
			
			// aapt resource value: 0x7F02010E
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave23 = 2130837774;
			
			// aapt resource value: 0x7F02010F
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave24 = 2130837775;
			
			// aapt resource value: 0x7F020110
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave25 = 2130837776;
			
			// aapt resource value: 0x7F020111
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave26 = 2130837777;
			
			// aapt resource value: 0x7F020112
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave27 = 2130837778;
			
			// aapt resource value: 0x7F020113
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave28 = 2130837779;
			
			// aapt resource value: 0x7F020114
			public const int PickUpDuallyChassisOpenFrameInTheBackMustHave29 = 2130837780;
			
			// aapt resource value: 0x7F020115
			public const int PickupFourWheel1 = 2130837781;
			
			// aapt resource value: 0x7F020116
			public const int PickupFourWheel10 = 2130837782;
			
			// aapt resource value: 0x7F020117
			public const int PickupFourWheel11 = 2130837783;
			
			// aapt resource value: 0x7F020118
			public const int PickupFourWheel12 = 2130837784;
			
			// aapt resource value: 0x7F020119
			public const int PickupFourWheel13 = 2130837785;
			
			// aapt resource value: 0x7F02011A
			public const int PickupFourWheel14 = 2130837786;
			
			// aapt resource value: 0x7F02011B
			public const int PickupFourWheel15 = 2130837787;
			
			// aapt resource value: 0x7F02011C
			public const int PickupFourWheel16 = 2130837788;
			
			// aapt resource value: 0x7F02011D
			public const int PickupFourWheel17 = 2130837789;
			
			// aapt resource value: 0x7F02011E
			public const int PickupFourWheel18 = 2130837790;
			
			// aapt resource value: 0x7F02011F
			public const int PickupFourWheel19 = 2130837791;
			
			// aapt resource value: 0x7F020120
			public const int PickupFourWheel2 = 2130837792;
			
			// aapt resource value: 0x7F020121
			public const int PickupFourWheel20 = 2130837793;
			
			// aapt resource value: 0x7F020122
			public const int PickupFourWheel21 = 2130837794;
			
			// aapt resource value: 0x7F020123
			public const int PickupFourWheel3 = 2130837795;
			
			// aapt resource value: 0x7F020124
			public const int PickupFourWheel4 = 2130837796;
			
			// aapt resource value: 0x7F020125
			public const int PickupFourWheel5 = 2130837797;
			
			// aapt resource value: 0x7F020126
			public const int PickupFourWheel6 = 2130837798;
			
			// aapt resource value: 0x7F020127
			public const int PickupFourWheel7 = 2130837799;
			
			// aapt resource value: 0x7F020128
			public const int PickupFourWheel8 = 2130837800;
			
			// aapt resource value: 0x7F020129
			public const int PickupFourWheel9 = 2130837801;
			
			// aapt resource value: 0x7F0201B0
			public const int scanCoupe = 2130837936;
			
			// aapt resource value: 0x7F0201B1
			public const int scanCruisemotorcycle = 2130837937;
			
			// aapt resource value: 0x7F0201B2
			public const int scanPickUp = 2130837938;
			
			// aapt resource value: 0x7F0201B3
			public const int scanPlate = 2130837939;
			
			// aapt resource value: 0x7F0201B4
			public const int scanSedan = 2130837940;
			
			// aapt resource value: 0x7F0201B5
			public const int scanSportbike = 2130837941;
			
			// aapt resource value: 0x7F0201B6
			public const int scanSuv = 2130837942;
			
			// aapt resource value: 0x7F0201B7
			public const int scanTouringmotorcycle = 2130837943;
			
			// aapt resource value: 0x7F0201B8
			public const int scanTricycle = 2130837944;
			
			// aapt resource value: 0x7F02012A
			public const int Sedan1 = 2130837802;
			
			// aapt resource value: 0x7F02012B
			public const int Sedan10 = 2130837803;
			
			// aapt resource value: 0x7F02012C
			public const int Sedan11 = 2130837804;
			
			// aapt resource value: 0x7F02012D
			public const int Sedan12 = 2130837805;
			
			// aapt resource value: 0x7F02012E
			public const int Sedan13 = 2130837806;
			
			// aapt resource value: 0x7F02012F
			public const int Sedan14 = 2130837807;
			
			// aapt resource value: 0x7F020130
			public const int Sedan15 = 2130837808;
			
			// aapt resource value: 0x7F020131
			public const int Sedan16 = 2130837809;
			
			// aapt resource value: 0x7F020132
			public const int Sedan17 = 2130837810;
			
			// aapt resource value: 0x7F020133
			public const int Sedan18 = 2130837811;
			
			// aapt resource value: 0x7F020134
			public const int Sedan19 = 2130837812;
			
			// aapt resource value: 0x7F020135
			public const int Sedan2 = 2130837813;
			
			// aapt resource value: 0x7F020136
			public const int Sedan20 = 2130837814;
			
			// aapt resource value: 0x7F020137
			public const int Sedan21 = 2130837815;
			
			// aapt resource value: 0x7F020138
			public const int Sedan22 = 2130837816;
			
			// aapt resource value: 0x7F020139
			public const int Sedan23 = 2130837817;
			
			// aapt resource value: 0x7F02013A
			public const int Sedan24 = 2130837818;
			
			// aapt resource value: 0x7F02013B
			public const int Sedan25 = 2130837819;
			
			// aapt resource value: 0x7F02013C
			public const int Sedan26 = 2130837820;
			
			// aapt resource value: 0x7F02013D
			public const int Sedan27 = 2130837821;
			
			// aapt resource value: 0x7F02013E
			public const int Sedan28 = 2130837822;
			
			// aapt resource value: 0x7F02013F
			public const int Sedan29 = 2130837823;
			
			// aapt resource value: 0x7F020140
			public const int Sedan3 = 2130837824;
			
			// aapt resource value: 0x7F020141
			public const int Sedan30 = 2130837825;
			
			// aapt resource value: 0x7F020142
			public const int Sedan31 = 2130837826;
			
			// aapt resource value: 0x7F020143
			public const int Sedan32 = 2130837827;
			
			// aapt resource value: 0x7F020144
			public const int Sedan33 = 2130837828;
			
			// aapt resource value: 0x7F020145
			public const int Sedan4 = 2130837829;
			
			// aapt resource value: 0x7F020146
			public const int Sedan5 = 2130837830;
			
			// aapt resource value: 0x7F020147
			public const int Sedan6 = 2130837831;
			
			// aapt resource value: 0x7F020148
			public const int Sedan7 = 2130837832;
			
			// aapt resource value: 0x7F020149
			public const int Sedan8 = 2130837833;
			
			// aapt resource value: 0x7F02014A
			public const int Sedan9 = 2130837834;
			
			// aapt resource value: 0x7F02014B
			public const int Sportbike1 = 2130837835;
			
			// aapt resource value: 0x7F02014C
			public const int Sportbike10 = 2130837836;
			
			// aapt resource value: 0x7F02014D
			public const int Sportbike11 = 2130837837;
			
			// aapt resource value: 0x7F02014E
			public const int Sportbike12 = 2130837838;
			
			// aapt resource value: 0x7F02014F
			public const int Sportbike13 = 2130837839;
			
			// aapt resource value: 0x7F020150
			public const int Sportbike14 = 2130837840;
			
			// aapt resource value: 0x7F020151
			public const int Sportbike15 = 2130837841;
			
			// aapt resource value: 0x7F020152
			public const int Sportbike16 = 2130837842;
			
			// aapt resource value: 0x7F020153
			public const int Sportbike17 = 2130837843;
			
			// aapt resource value: 0x7F020154
			public const int Sportbike18 = 2130837844;
			
			// aapt resource value: 0x7F020155
			public const int Sportbike19 = 2130837845;
			
			// aapt resource value: 0x7F020156
			public const int Sportbike2 = 2130837846;
			
			// aapt resource value: 0x7F020157
			public const int Sportbike3 = 2130837847;
			
			// aapt resource value: 0x7F020158
			public const int Sportbike4 = 2130837848;
			
			// aapt resource value: 0x7F020159
			public const int Sportbike5 = 2130837849;
			
			// aapt resource value: 0x7F02015A
			public const int Sportbike6 = 2130837850;
			
			// aapt resource value: 0x7F02015B
			public const int Sportbike7 = 2130837851;
			
			// aapt resource value: 0x7F02015C
			public const int Sportbike8 = 2130837852;
			
			// aapt resource value: 0x7F02015D
			public const int Sportbike9 = 2130837853;
			
			// aapt resource value: 0x7F0201B9
			public const int startVideo = 2130837945;
			
			// aapt resource value: 0x7F0201BA
			public const int stopVideo = 2130837946;
			
			// aapt resource value: 0x7F02015E
			public const int Suv1 = 2130837854;
			
			// aapt resource value: 0x7F02015F
			public const int Suv10 = 2130837855;
			
			// aapt resource value: 0x7F020160
			public const int Suv11 = 2130837856;
			
			// aapt resource value: 0x7F020161
			public const int Suv12 = 2130837857;
			
			// aapt resource value: 0x7F020162
			public const int Suv13 = 2130837858;
			
			// aapt resource value: 0x7F020163
			public const int Suv14 = 2130837859;
			
			// aapt resource value: 0x7F020164
			public const int Suv15 = 2130837860;
			
			// aapt resource value: 0x7F020165
			public const int Suv16 = 2130837861;
			
			// aapt resource value: 0x7F020166
			public const int Suv17 = 2130837862;
			
			// aapt resource value: 0x7F020167
			public const int Suv18 = 2130837863;
			
			// aapt resource value: 0x7F020168
			public const int Suv19 = 2130837864;
			
			// aapt resource value: 0x7F020169
			public const int Suv2 = 2130837865;
			
			// aapt resource value: 0x7F02016A
			public const int Suv20 = 2130837866;
			
			// aapt resource value: 0x7F02016B
			public const int Suv21 = 2130837867;
			
			// aapt resource value: 0x7F02016C
			public const int Suv22 = 2130837868;
			
			// aapt resource value: 0x7F02016D
			public const int Suv23 = 2130837869;
			
			// aapt resource value: 0x7F02016E
			public const int Suv24 = 2130837870;
			
			// aapt resource value: 0x7F02016F
			public const int Suv25 = 2130837871;
			
			// aapt resource value: 0x7F020170
			public const int Suv26 = 2130837872;
			
			// aapt resource value: 0x7F020171
			public const int Suv27 = 2130837873;
			
			// aapt resource value: 0x7F020172
			public const int Suv28 = 2130837874;
			
			// aapt resource value: 0x7F020173
			public const int Suv29 = 2130837875;
			
			// aapt resource value: 0x7F020174
			public const int Suv3 = 2130837876;
			
			// aapt resource value: 0x7F020175
			public const int Suv30 = 2130837877;
			
			// aapt resource value: 0x7F020176
			public const int Suv31 = 2130837878;
			
			// aapt resource value: 0x7F020177
			public const int Suv32 = 2130837879;
			
			// aapt resource value: 0x7F020178
			public const int Suv33 = 2130837880;
			
			// aapt resource value: 0x7F020179
			public const int Suv34 = 2130837881;
			
			// aapt resource value: 0x7F02017A
			public const int Suv35 = 2130837882;
			
			// aapt resource value: 0x7F02017B
			public const int Suv36 = 2130837883;
			
			// aapt resource value: 0x7F02017C
			public const int Suv4 = 2130837884;
			
			// aapt resource value: 0x7F02017D
			public const int Suv5 = 2130837885;
			
			// aapt resource value: 0x7F02017E
			public const int Suv6 = 2130837886;
			
			// aapt resource value: 0x7F02017F
			public const int Suv7 = 2130837887;
			
			// aapt resource value: 0x7F020180
			public const int Suv8 = 2130837888;
			
			// aapt resource value: 0x7F020181
			public const int Suv9 = 2130837889;
			
			// aapt resource value: 0x7F020182
			public const int Take = 2130837890;
			
			// aapt resource value: 0x7F020183
			public const int TakeArow = 2130837891;
			
			// aapt resource value: 0x7F020184
			public const int Touringmotorcycle1 = 2130837892;
			
			// aapt resource value: 0x7F020185
			public const int Touringmotorcycle10 = 2130837893;
			
			// aapt resource value: 0x7F020186
			public const int Touringmotorcycle11 = 2130837894;
			
			// aapt resource value: 0x7F020187
			public const int Touringmotorcycle12 = 2130837895;
			
			// aapt resource value: 0x7F020188
			public const int Touringmotorcycle13 = 2130837896;
			
			// aapt resource value: 0x7F020189
			public const int Touringmotorcycle14 = 2130837897;
			
			// aapt resource value: 0x7F02018A
			public const int Touringmotorcycle2 = 2130837898;
			
			// aapt resource value: 0x7F02018B
			public const int Touringmotorcycle3 = 2130837899;
			
			// aapt resource value: 0x7F02018C
			public const int Touringmotorcycle4 = 2130837900;
			
			// aapt resource value: 0x7F02018D
			public const int Touringmotorcycle5 = 2130837901;
			
			// aapt resource value: 0x7F02018E
			public const int Touringmotorcycle6 = 2130837902;
			
			// aapt resource value: 0x7F02018F
			public const int Touringmotorcycle7 = 2130837903;
			
			// aapt resource value: 0x7F020190
			public const int Touringmotorcycle8 = 2130837904;
			
			// aapt resource value: 0x7F020191
			public const int Touringmotorcycle9 = 2130837905;
			
			// aapt resource value: 0x7F020192
			public const int Tricycle1 = 2130837906;
			
			// aapt resource value: 0x7F020193
			public const int Tricycle10 = 2130837907;
			
			// aapt resource value: 0x7F020194
			public const int Tricycle11 = 2130837908;
			
			// aapt resource value: 0x7F020195
			public const int Tricycle12 = 2130837909;
			
			// aapt resource value: 0x7F020196
			public const int Tricycle13 = 2130837910;
			
			// aapt resource value: 0x7F020197
			public const int Tricycle14 = 2130837911;
			
			// aapt resource value: 0x7F020198
			public const int Tricycle15 = 2130837912;
			
			// aapt resource value: 0x7F020199
			public const int Tricycle16 = 2130837913;
			
			// aapt resource value: 0x7F02019A
			public const int Tricycle17 = 2130837914;
			
			// aapt resource value: 0x7F02019B
			public const int Tricycle18 = 2130837915;
			
			// aapt resource value: 0x7F02019C
			public const int Tricycle19 = 2130837916;
			
			// aapt resource value: 0x7F02019D
			public const int Tricycle2 = 2130837917;
			
			// aapt resource value: 0x7F02019E
			public const int Tricycle20 = 2130837918;
			
			// aapt resource value: 0x7F02019F
			public const int Tricycle21 = 2130837919;
			
			// aapt resource value: 0x7F0201A0
			public const int Tricycle22 = 2130837920;
			
			// aapt resource value: 0x7F0201A1
			public const int Tricycle23 = 2130837921;
			
			// aapt resource value: 0x7F0201A2
			public const int Tricycle3 = 2130837922;
			
			// aapt resource value: 0x7F0201A3
			public const int Tricycle4 = 2130837923;
			
			// aapt resource value: 0x7F0201A4
			public const int Tricycle5 = 2130837924;
			
			// aapt resource value: 0x7F0201A5
			public const int Tricycle6 = 2130837925;
			
			// aapt resource value: 0x7F0201A6
			public const int Tricycle7 = 2130837926;
			
			// aapt resource value: 0x7F0201A7
			public const int Tricycle8 = 2130837927;
			
			// aapt resource value: 0x7F0201A8
			public const int Tricycle9 = 2130837928;
			
			// aapt resource value: 0x7F0201BB
			public const int trup = 2130837947;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int background = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int progress = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int secondaryProgress = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int sliding_tabs = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int toolbar = 2130903044;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
